baseURL = ""
languageCode = "en-us"
title = "DanRovito.com"
theme = "dan"
copyright = "&copy; {year} Dan Rovito"
relativeURLs = true
pluralizelisttitles = false
[blackfriday]
 smartypants = false

[permalinks]
  blog = "blog/:filename/"

[[menu.main]]
    name = "Blog"
    weight = 20
    url = "/blog/"

[[menu.main]]
    name = "About"
    weight = 200
    url = "/about/"

[[menu.main]]
    name = "Projects"
    weight = 200
    url = "/projects/"