baseURL = "https://staging.danrovito.com"
languageCode = "en-us"
title = "DanRovito.com"
theme = "dan"
copyright = "&copy; {year} Dan Rovito"
relativeURLs = true
pluralizelisttitles = false
canonifyURLs = true
enableRobotsTXT = true
[markup.goldmark.renderer]
 unsafe= true
[blackfriday]
 smartypants = false

[permalinks]
  blog = "blog/:filename/"

[[menu.main]]
    name = "Blog"
    weight = 20
    url = "/blog/"

[[menu.main]]
    name = "About"
    weight = 200
    url = "/about/"

[[menu.main]]
    name = "Projects"
    weight = 201
    url = "/projects/"

[[menu.main]]
    name = "Uses"
    weight = 202
    url = "/uses/"