baseURL = ""
languageCode = "en-us"
title = "Dan Rovito"
theme = "dan"
relativeURLs = true
[blackfriday]
 smartypants = false

[permalinks]
  blog = "blog/:filename/"

[[menu.main]]
    name = "Blog"
    weight = 20
    url = "/blog/"